[package]
name = "Day8"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
glam = "0.22.0"
itertools = "0.10.5"
miette = "5.8.0"
nom = "7.1.0"
nom_locate = "4.0.0"
tracing = "0.1.37"
tracing-subscriber = "0.3"
util = { path = "../util" }